In [8]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
pd.options.display.max_rows = 100

In [9]:
df = pd.read_csv('ex5.csv', index_col='Object').to_numpy()
df

array([[20, 20,  0],
       [17, 11,  1],
       [ 1,  8,  2],
       [11, 11,  0],
       [13, 18,  1],
       [ 1,  9,  2],
       [ 7, 18,  1],
       [ 7,  4,  0],
       [ 5,  6,  2],
       [ 5,  5,  2],
       [12,  6,  2],
       [18,  4,  0],
       [20, 14,  1],
       [ 6, 14,  2],
       [ 7, 19,  2]])

In [10]:
X = df[:, 0:2]
Y = df[:, 2]
print(X, Y)

[[20 20]
 [17 11]
 [ 1  8]
 [11 11]
 [13 18]
 [ 1  9]
 [ 7 18]
 [ 7  4]
 [ 5  6]
 [ 5  5]
 [12  6]
 [18  4]
 [20 14]
 [ 6 14]
 [ 7 19]] [0 1 2 0 1 2 1 0 2 2 2 0 1 2 2]


In [11]:
mean = KMeans(n_clusters = 3, init = np.array([[14.0, 9.75], [14.25, 15.25], [5.29, 9.57]]), max_iter = 100, n_init = 1)

In [12]:
model = mean.fit(X)

In [26]:
clusters = np.array(model.labels_.tolist())
clusters

array([1, 0, 2, 0, 1, 2, 1, 2, 2, 2, 0, 0, 1, 2, 1])

In [27]:
alldistances = mean.fit_transform(X)
alldistances

array([[13.20037878,  6.95701085, 20.07001633],
       [ 3.90512484,  7.69415362, 13.25916874],
       [13.5       , 15.80506248,  3.1841622 ],
       [ 4.60977223,  7.21110255,  7.60299649],
       [10.11187421,  0.4472136 , 13.59432071],
       [13.53698637, 15.20526225,  3.43592135],
       [12.5       ,  6.40312424, 10.71473544],
       [ 8.5       , 15.2118375 ,  4.63381292],
       [ 9.70824392, 14.48447445,  1.86338998],
       [ 9.96242942, 15.31012737,  2.79384244],
       [ 3.20156212, 11.88276062,  8.00867585],
       [ 5.31507291, 14.54647724, 14.31102916],
       [ 8.1394103 ,  7.61577311, 17.05302189],
       [10.40432602,  8.31865374,  6.59334681],
       [13.31352696,  6.51152824, 11.68213261]])

In [39]:
distances = alldistances[:, 0]
distances

array([13.20037878,  3.90512484, 13.5       ,  4.60977223, 10.11187421,
       13.53698637, 12.5       ,  8.5       ,  9.70824392,  9.96242942,
        3.20156212,  5.31507291,  8.1394103 , 10.40432602, 13.31352696])

In [40]:
indicies = np.where(clusters == 0)
indicies

(array([ 1,  3, 10, 11]),)

In [41]:
distances[indicies].mean()

4.25788302292088